import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import { ShoppingCartContextProvider } from "@/context/ShoppingCartContext";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Mehdi Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ShoppingCartContextProvider>
          <Layout>{children}</Layout>
          <ToastContainer />
        </ShoppingCartContextProvider>
      </body>
    </html>
  );
}
